version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nuxtts-boilerplate
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    working_dir: /var/www
    volumes:
      - ./app:/var/www
